### ISSUE TITLE
please give me a hand 

### ISSUE THREAD

**Issue by b850617** [jaycreate/Ionic-MySQL#1]
how could I start the server ???

**Comment by jaycreate** [comment]
for server, you have to start apache web server keeping it running. 
try simple php script and see if it work. then you have to test the application on your mobile, I not work on simulation.

**Comment by jaycreate** [comment]
For more information, how to install webserver and start service.
https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu

**Comment by b850617** [comment]
thx u so much
